name:                lab1
version:             0.1.0.0
github:              "SymphonyOfTranquility/Functional-programming"
license:             BSD3
author:              "SymphonyOfTranquility"
maintainer:          "example@example.com"
copyright:           "2021 SymphonyOfTranquility"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SymphonyOfTranquility/Functional-programming>

dependencies:
- base >= 4.7 && < 5
- mysql-haskell == 0.8.4.3
- io-streams == 1.5.2.0
- text == 1.2.4.0

library:
  source-dirs: src

executables:
  lab1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab1

tests:
  lab1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab1
